"""Paired validation of deterministic and CVaR outage schedules.

Both final schedules are evaluated on one common bank of operating-state
samples.  Every sample has the same source period, nodal-demand vector,
probability, and contingency catalogue for both schedules.  The default sample
bank is generated by correlated Gaussian perturbations around the three most
critical no-maintenance operating states of the full planning horizon.

The primary loss is aligned with the optimisation engines:

``loss = max_incremental_DNS + w_total * mean_incremental_summed_nodal_DNS``.

The no-maintenance baseline is solved at the same demand and with the same
effective contingency set as the candidate schedule.
"""
from __future__ import annotations

import argparse
import json
import logging
import math
import os
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np

from .critical_state_selector import CriticalStateSelector
from .master_problem import build_active_outages
from .outage_clusters import OutageCluster
from .risk_metrics import weighted_var_cvar
from .scenario_sampling import (
    DemandScenario,
    EmpiricalClusterScenarioSampler,
    GaussianCriticalStateScenarioSampler,
    demand_fingerprint,
)
from .serialization import json_safe

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PairedValidationConfig:
    scenario_count: int = 96
    scenario_seed: int = 20260727
    scenario_model: str = "gaussian_critical_states"
    critical_state_count: int = 3
    representative_state_mode: str = "network_screening"
    representative_candidate_times: int = 24
    gaussian_relative_sigma: float = 0.05
    gaussian_global_sigma: float = 0.03
    gaussian_correlation_shrinkage: float = 0.20
    gaussian_antithetic: bool = True
    sampling_scheme: str = "random"
    global_lognormal_sigma: float = 0.05
    total_dns_component_weight: float = 0.10
    cvar_alpha: float = 0.95
    oracle_workers: int = 1
    winner_tolerance_mw: float = 1e-6


@dataclass(frozen=True)
class ScheduleSampleEvaluation:
    formulation: str
    scenario_id: str
    probability: float
    source_time: str
    anchor_rank: int
    sampling_model: str
    total_demand: float
    global_multiplier: float
    active_outages: tuple[str, ...]
    effective_contingencies: tuple[str, ...]
    candidate_maximum_dns: float
    candidate_total_dns: float
    candidate_worst_contingency: str | None
    baseline_maximum_dns: float
    baseline_total_dns: float
    incremental_maximum_dns: float
    incremental_total_dns: float
    mean_incremental_dns: float
    loss: float

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _load_json(path: str | Path) -> dict[str, Any]:
    source = Path(path)
    if not source.exists():
        raise FileNotFoundError(source)
    data = json.loads(source.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError(f"Expected a JSON object in {source}.")
    return data


def active_outages_from_schedule(
    data: Mapping[str, Any],
    schedule: Mapping[str, str],
    deferred_outages: Sequence[str] = (),
) -> dict[str, tuple[str, ...]]:
    """Expand validated start decisions into active outage sets."""
    deferred = {str(outage) for outage in deferred_outages}
    expected = set(data["names"]["outages"]) - deferred
    missing = expected - set(schedule)
    if missing:
        raise ValueError(
            "The schedule does not define starting periods for: "
            + ", ".join(sorted(missing))
        )
    return build_active_outages(data, schedule)


def build_common_validation_samples(
    data: Mapping[str, Any],
    config: PairedValidationConfig,
    *,
    oracle=None,
) -> tuple[list[DemandScenario], dict[str, float], tuple[dict[str, Any], ...]]:
    """Create a schedule-independent operating-state sample bank."""
    times = tuple(str(time) for time in data["T"])
    horizon_cluster = OutageCluster(
        cluster_id="paired_validation_horizon",
        start_index=0,
        end_index=len(times),
        times=times,
        active_outages=(),
    )

    if config.scenario_model == "gaussian_critical_states":
        if oracle is None:
            from .cluster_scopf_oracle import ClusterSCOPFOracle

            oracle = ClusterSCOPFOracle(data)
        selector = CriticalStateSelector(
            data,
            oracle,
            mode=config.representative_state_mode,
            candidate_times=config.representative_candidate_times,
        )
        representatives = selector.select_many(
            horizon_cluster, count=config.critical_state_count
        )
        sampler = GaussianCriticalStateScenarioSampler(
            data,
            scenario_count=config.scenario_count,
            seed=config.scenario_seed,
            relative_sigma=config.gaussian_relative_sigma,
            global_sigma=config.gaussian_global_sigma,
            correlation_shrinkage=config.gaussian_correlation_shrinkage,
            antithetic=config.gaussian_antithetic,
        )
        samples = sampler.scenarios_for_cluster(
            horizon_cluster, representatives
        )
        representative_metadata = tuple(asdict(item) for item in representatives)
    elif config.scenario_model == "empirical_cluster":
        sampler = EmpiricalClusterScenarioSampler(
            data,
            scenario_count=config.scenario_count,
            seed=config.scenario_seed,
            global_lognormal_sigma=config.global_lognormal_sigma,
            sampling_scheme=config.sampling_scheme,
        )
        samples = sampler.scenarios_for_cluster(horizon_cluster)
        representative_metadata = ()
    else:
        raise ValueError(
            "scenario_model must be 'gaussian_critical_states' or "
            "'empirical_cluster'."
        )
    return samples, sampler.probability_mapping(), representative_metadata


def _probability_of_positive_loss(
    losses: Mapping[str, float],
    probabilities: Mapping[str, float],
    *,
    tolerance: float = 1e-9,
) -> float:
    total = float(sum(probabilities.values()))
    if total <= 0.0:
        return 0.0
    return float(
        sum(
            float(probabilities[scenario_id])
            for scenario_id, loss in losses.items()
            if float(loss) > tolerance
        )
        / total
    )


def _weighted_cdf(
    losses: Mapping[str, float],
    probabilities: Mapping[str, float],
    grid: np.ndarray,
) -> np.ndarray:
    total = float(sum(probabilities.values()))
    if total <= 0.0:
        return np.zeros_like(grid, dtype=float)
    return np.asarray(
        [
            sum(
                float(probabilities[scenario_id])
                for scenario_id, loss in losses.items()
                if float(loss) <= float(point) + 1e-12
            )
            / total
            for point in grid
        ],
        dtype=float,
    )


def stochastic_dominance(
    deterministic_losses: Mapping[str, float],
    cvar_losses: Mapping[str, float],
    probabilities: Mapping[str, float],
    *,
    tolerance: float = 1e-9,
) -> str:
    """Return first-order dominance classification; lower loss is preferred."""
    grid = np.asarray(
        sorted(
            set(float(value) for value in deterministic_losses.values())
            | set(float(value) for value in cvar_losses.values())
        ),
        dtype=float,
    )
    if grid.size == 0:
        return "identical"
    det_cdf = _weighted_cdf(deterministic_losses, probabilities, grid)
    cvar_cdf = _weighted_cdf(cvar_losses, probabilities, grid)
    cvar_dominates = bool(
        np.all(cvar_cdf + tolerance >= det_cdf)
        and np.any(cvar_cdf > det_cdf + tolerance)
    )
    det_dominates = bool(
        np.all(det_cdf + tolerance >= cvar_cdf)
        and np.any(det_cdf > cvar_cdf + tolerance)
    )
    if cvar_dominates:
        return "cvar"
    if det_dominates:
        return "deterministic"
    if np.allclose(det_cdf, cvar_cdf, atol=tolerance, rtol=0.0):
        return "identical"
    return "crossing"


def compare_paired_losses(
    deterministic_losses: Mapping[str, float],
    cvar_losses: Mapping[str, float],
    probabilities: Mapping[str, float],
    *,
    alpha: float,
    winner_tolerance_mw: float = 1e-6,
) -> dict[str, Any]:
    """Calculate directly comparable risk metrics and a transparent verdict."""
    if set(deterministic_losses) != set(cvar_losses):
        raise ValueError("Both schedules must use identical scenario IDs.")
    if set(deterministic_losses) != set(probabilities):
        raise ValueError("Losses and probabilities must use identical IDs.")

    det_risk = weighted_var_cvar(
        deterministic_losses, probabilities, alpha=alpha
    )
    cvar_risk = weighted_var_cvar(cvar_losses, probabilities, alpha=alpha)
    difference = {
        scenario_id: float(cvar_losses[scenario_id])
        - float(deterministic_losses[scenario_id])
        for scenario_id in deterministic_losses
    }
    total_probability = float(sum(probabilities.values()))
    cvar_better_probability = sum(
        float(probabilities[scenario_id])
        for scenario_id, value in difference.items()
        if value < -winner_tolerance_mw
    ) / total_probability
    deterministic_better_probability = sum(
        float(probabilities[scenario_id])
        for scenario_id, value in difference.items()
        if value > winner_tolerance_mw
    ) / total_probability
    tie_probability = max(
        0.0, 1.0 - cvar_better_probability - deterministic_better_probability
    )

    cvar_difference = float(cvar_risk.cvar - det_risk.cvar)
    if cvar_difference < -winner_tolerance_mw:
        winner = "cvar"
        conclusion = (
            "The CVaR schedule has lower paired validation tail risk: "
            f"CVaR is reduced by {-cvar_difference:.6g} MW."
        )
    elif cvar_difference > winner_tolerance_mw:
        winner = "deterministic"
        conclusion = (
            "The deterministic schedule has lower paired validation tail risk: "
            f"the CVaR schedule increases CVaR by {cvar_difference:.6g} MW."
        )
    else:
        winner = "tie"
        conclusion = (
            "The schedules are tied in paired validation CVaR within the "
            f"configured tolerance of {winner_tolerance_mw:.6g} MW."
        )

    det_cvar = float(det_risk.cvar)
    relative_reduction = (
        100.0 * (det_cvar - float(cvar_risk.cvar)) / det_cvar
        if det_cvar > winner_tolerance_mw
        else math.nan
    )

    return {
        "alpha": float(alpha),
        "primary_decision_metric": "paired_validation_composite_dns_cvar_mw",
        "tail_risk_winner": winner,
        "conclusion": conclusion,
        "deterministic": {
            **asdict(det_risk),
            "maximum_loss": float(
                max(deterministic_losses.values(), default=0.0)
            ),
            "probability_positive_loss": _probability_of_positive_loss(
                deterministic_losses, probabilities
            ),
        },
        "cvar": {
            **asdict(cvar_risk),
            "maximum_loss": float(max(cvar_losses.values(), default=0.0)),
            "probability_positive_loss": _probability_of_positive_loss(
                cvar_losses, probabilities
            ),
        },
        "cvar_minus_deterministic": {
            "expected_loss_mw": float(
                cvar_risk.expected_loss - det_risk.expected_loss
            ),
            "var_mw": float(cvar_risk.var - det_risk.var),
            "cvar_mw": cvar_difference,
            "maximum_loss_mw": float(
                max(cvar_losses.values(), default=0.0)
                - max(deterministic_losses.values(), default=0.0)
            ),
        },
        "cvar_reduction_relative_to_deterministic_percent": relative_reduction,
        "paired_sample_outcomes": {
            "probability_cvar_better": float(cvar_better_probability),
            "probability_deterministic_better": float(
                deterministic_better_probability
            ),
            "probability_tie": float(tie_probability),
            "cvar_better_count": int(
                sum(value < -winner_tolerance_mw for value in difference.values())
            ),
            "deterministic_better_count": int(
                sum(value > winner_tolerance_mw for value in difference.values())
            ),
            "tie_count": int(
                sum(abs(value) <= winner_tolerance_mw for value in difference.values())
            ),
        },
        "first_order_stochastic_dominance": stochastic_dominance(
            deterministic_losses,
            cvar_losses,
            probabilities,
            tolerance=winner_tolerance_mw,
        ),
        "paired_differences_mw": difference,
    }


def load_validation_data(
    config_path: str | Path,
    data_overrides_config: str | Path | None = None,
) -> dict[str, Any]:
    """Load and configure the same network model used by both schedulers."""
    from .runtime import apply_data_overrides_from_json, configured_decomposition_data

    data = configured_decomposition_data(config_path, allow_outage_deferral=True)
    return apply_data_overrides_from_json(data, data_overrides_config)


def evaluate_paired_schedules(
    data: Mapping[str, Any],
    deterministic_results: Mapping[str, Any],
    cvar_results: Mapping[str, Any],
    config: PairedValidationConfig,
) -> dict[str, Any]:
    """Evaluate both schedules on one common, fixed operating-state bank."""
    from .cluster_scopf_oracle import ClusterSCOPFOracle

    schedules = {
        "deterministic": deterministic_results.get("best_schedule") or {},
        "cvar": cvar_results.get("best_schedule") or {},
    }
    if not schedules["deterministic"] or not schedules["cvar"]:
        raise ValueError(
            "Both result files must contain a non-empty best_schedule."
        )

    active_by_formulation = {
        "deterministic": active_outages_from_schedule(
            data,
            schedules["deterministic"],
            deterministic_results.get("deferred_outages") or (),
        ),
        "cvar": active_outages_from_schedule(
            data,
            schedules["cvar"],
            cvar_results.get("deferred_outages") or (),
        ),
    }
    oracle = ClusterSCOPFOracle(data)
    samples, probabilities, representatives = build_common_validation_samples(
        data, config, oracle=oracle
    )
    all_contingencies = tuple(data["names"].get("contingencies", ()))

    baseline_cache: dict[tuple[str, tuple[str, ...]], Any] = {}
    candidate_cache: dict[tuple[str, tuple[str, ...], tuple[str, ...]], Any] = {}
    cache_lock = threading.Lock()
    baseline_key_locks: dict[tuple[str, tuple[str, ...]], threading.Lock] = {}
    candidate_key_locks: dict[
        tuple[str, tuple[str, ...], tuple[str, ...]], threading.Lock
    ] = {}

    def solve_one(
        formulation: str,
        sample: DemandScenario,
    ) -> ScheduleSampleEvaluation:
        active = active_by_formulation[formulation][sample.source_time]
        effective = oracle.effective_contingencies(active, all_contingencies)
        demand_key = demand_fingerprint(sample.demand)
        candidate_key = (demand_key, tuple(sorted(active)), tuple(effective))
        with cache_lock:
            candidate = candidate_cache.get(candidate_key)
            candidate_lock = candidate_key_locks.setdefault(
                candidate_key, threading.Lock()
            )
        if candidate is None:
            with candidate_lock:
                with cache_lock:
                    candidate = candidate_cache.get(candidate_key)
                if candidate is None:
                    candidate = oracle.solve(sample.source_time, active, contingencies=effective,
                                             demand_override=sample.demand)
                    with cache_lock:
                        candidate_cache[candidate_key] = candidate
        if not math.isfinite(candidate.maximum_dns):
            raise RuntimeError(
                f"Candidate SCOPF failed for {formulation}, "
                f"{sample.scenario_id}."
            )

        cache_key = (demand_key, tuple(effective))
        with cache_lock:
            baseline = baseline_cache.get(cache_key)
            key_lock = baseline_key_locks.setdefault(cache_key, threading.Lock())
        if baseline is None:
            with key_lock:
                with cache_lock:
                    baseline = baseline_cache.get(cache_key)
                if baseline is None:
                    baseline = oracle.solve(sample.source_time, (), contingencies=effective,
                                            demand_override=sample.demand)
                    if not math.isfinite(baseline.maximum_dns):
                        raise RuntimeError(
                            f"Baseline SCOPF failed for {formulation}, "
                            f"{sample.scenario_id}."
                        )
                    with cache_lock:
                        baseline_cache[cache_key] = baseline

        maximum_increment = max(
            0.0, float(candidate.maximum_dns - baseline.maximum_dns)
        )
        total_increment = max(
            0.0, float(candidate.total_dns - baseline.total_dns)
        )
        mean_increment = total_increment / max(
            1, len(candidate.contingencies) + 1
        )
        loss = (
            maximum_increment
            + config.total_dns_component_weight * mean_increment
        )
        return ScheduleSampleEvaluation(
            formulation=formulation,
            scenario_id=sample.scenario_id,
            probability=float(sample.probability),
            source_time=sample.source_time,
            anchor_rank=sample.anchor_rank,
            sampling_model=sample.sampling_model,
            total_demand=float(sample.total_demand),
            global_multiplier=float(sample.global_multiplier),
            active_outages=tuple(active),
            effective_contingencies=tuple(effective),
            candidate_maximum_dns=float(candidate.maximum_dns),
            candidate_total_dns=float(candidate.total_dns),
            candidate_worst_contingency=candidate.worst_contingency,
            baseline_maximum_dns=float(baseline.maximum_dns),
            baseline_total_dns=float(baseline.total_dns),
            incremental_maximum_dns=float(maximum_increment),
            incremental_total_dns=float(total_increment),
            mean_incremental_dns=float(mean_increment),
            loss=float(loss),
        )

    tasks = [
        (formulation, sample)
        for sample in samples
        for formulation in ("deterministic", "cvar")
    ]
    evaluations: list[ScheduleSampleEvaluation] = []
    workers = max(1, int(config.oracle_workers))
    if workers == 1:
        for index, (formulation, sample) in enumerate(tasks, start=1):
            logger.info(
                "Paired validation %d/%d: %s %s (%s)",
                index,
                len(tasks),
                formulation,
                sample.scenario_id,
                sample.source_time,
            )
            evaluations.append(solve_one(formulation, sample))
    else:
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {
                executor.submit(solve_one, formulation, sample): (
                    formulation,
                    sample.scenario_id,
                )
                for formulation, sample in tasks
            }
            for completed, future in enumerate(as_completed(futures), start=1):
                formulation, scenario_id = futures[future]
                logger.info(
                    "Paired validation %d/%d completed: %s %s",
                    completed,
                    len(tasks),
                    formulation,
                    scenario_id,
                )
                evaluations.append(future.result())

    evaluations.sort(key=lambda item: (item.scenario_id, item.formulation))
    by_formulation = {
        formulation: [
            evaluation
            for evaluation in evaluations
            if evaluation.formulation == formulation
        ]
        for formulation in ("deterministic", "cvar")
    }
    losses = {
        formulation: {
            evaluation.scenario_id: evaluation.loss
            for evaluation in records
        }
        for formulation, records in by_formulation.items()
    }
    comparison = compare_paired_losses(
        losses["deterministic"],
        losses["cvar"],
        probabilities,
        alpha=config.cvar_alpha,
        winner_tolerance_mw=config.winner_tolerance_mw,
    )

    return {
        "validation_design": {
            "description": (
                "Both schedules are evaluated on identical fixed operating-state "
                "samples. Each sample has the same critical-state anchor, nodal "
                "demand, probability, and contingency catalogue for both schedules."
            ),
            "loss_definition": (
                "positive incremental maximum DNS plus "
                "total_dns_component_weight times mean positive incremental "
                "summed nodal DNS over normal and N-1 states"
            ),
            "config": asdict(config),
            "configured_contingency_count": len(all_contingencies),
            "critical_validation_states": representatives,
            "scenario_probabilities": probabilities,
            "scenario_bank": [
                {
                    "scenario_id": sample.scenario_id,
                    "probability": sample.probability,
                    "source_time": sample.source_time,
                    "anchor_rank": sample.anchor_rank,
                    "sampling_model": sample.sampling_model,
                    "total_demand": sample.total_demand,
                    "global_multiplier": sample.global_multiplier,
                    "demand_fingerprint": demand_fingerprint(sample.demand),
                }
                for sample in samples
            ],
        },
        "comparison": comparison,
        "performance": {
            "oracle_statistics": oracle.statistics(),
            "unique_candidate_states": len(candidate_cache),
            "unique_baseline_states": len(baseline_cache),
            "requested_schedule_sample_evaluations": len(tasks),
        },
        "deterministic_evaluations": [
            record.to_dict() for record in by_formulation["deterministic"]
        ],
        "cvar_evaluations": [
            record.to_dict() for record in by_formulation["cvar"]
        ],
    }


def save_paired_validation(
    result: Mapping[str, Any],
    path: str | Path,
) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(json_safe(result), indent=2, allow_nan=False),
        encoding="utf-8",
    )
    return destination


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deterministic-results", required=True, type=Path)
    parser.add_argument("--cvar-results", required=True, type=Path)
    parser.add_argument(
        "--config",
        type=Path,
        default=Path(
            os.getenv(
                "PROPER_SCHEDULER_CONFIG",
                "./config/conf_IEEE24_scheduler_v2.json",
            )
        ),
        help="Scheduler input configuration used to reconstruct the network.",
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--data-overrides-config", type=Path, help="Clustered JSON used to reproduce data overrides/benchmark slices.")
    parser.add_argument("--scenario-count", type=int, default=96)
    parser.add_argument("--scenario-seed", type=int, default=20260727)
    parser.add_argument(
        "--scenario-model",
        choices=("gaussian_critical_states", "empirical_cluster"),
        default="gaussian_critical_states",
    )
    parser.add_argument("--critical-state-count", type=int, default=3)
    parser.add_argument(
        "--sampling-scheme",
        choices=("random", "stratified_tail"),
        default="random",
    )
    parser.add_argument("--global-lognormal-sigma", type=float, default=None)
    parser.add_argument("--gaussian-relative-sigma", type=float, default=None)
    parser.add_argument("--gaussian-global-sigma", type=float, default=None)
    parser.add_argument("--cvar-alpha", type=float, default=None)
    parser.add_argument("--oracle-workers", type=int, default=1)
    parser.add_argument("--winner-tolerance-mw", type=float, default=1e-6)
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    logging.basicConfig(
        format="%(asctime)s::%(levelname)s::%(name)s::%(message)s",
        level=logging.INFO,
    )
    args = _parser().parse_args(argv)
    deterministic_results = _load_json(args.deterministic_results)
    cvar_results = _load_json(args.cvar_results)
    cvar_config = cvar_results.get("config") or {}

    config = PairedValidationConfig(
        scenario_count=int(args.scenario_count),
        scenario_seed=int(args.scenario_seed),
        scenario_model=str(args.scenario_model),
        critical_state_count=int(args.critical_state_count),
        sampling_scheme=str(args.sampling_scheme),
        global_lognormal_sigma=(
            float(args.global_lognormal_sigma)
            if args.global_lognormal_sigma is not None
            else float(cvar_config.get("global_lognormal_sigma", 0.05))
        ),
        gaussian_relative_sigma=(
            float(args.gaussian_relative_sigma)
            if args.gaussian_relative_sigma is not None
            else float(cvar_config.get("gaussian_relative_sigma", 0.05))
        ),
        gaussian_global_sigma=(
            float(args.gaussian_global_sigma)
            if args.gaussian_global_sigma is not None
            else float(cvar_config.get("gaussian_global_sigma", 0.03))
        ),
        gaussian_correlation_shrinkage=float(
            cvar_config.get("gaussian_correlation_shrinkage", 0.20)
        ),
        gaussian_antithetic=bool(
            cvar_config.get("gaussian_antithetic", True)
        ),
        total_dns_component_weight=float(
            cvar_config.get("total_dns_component_weight", 0.10)
        ),
        cvar_alpha=(
            float(args.cvar_alpha)
            if args.cvar_alpha is not None
            else float(cvar_config.get("cvar_alpha", 0.95))
        ),
        oracle_workers=int(args.oracle_workers),
        winner_tolerance_mw=float(args.winner_tolerance_mw),
    )
    data = load_validation_data(args.config, args.data_overrides_config)
    result = evaluate_paired_schedules(
        data,
        deterministic_results,
        cvar_results,
        config,
    )
    output = save_paired_validation(result, args.output)
    comparison = result["comparison"]
    logger.info("Paired validation written to %s", output)
    logger.info("Tail-risk winner: %s", comparison["tail_risk_winner"])
    logger.info("Conclusion: %s", comparison["conclusion"])


if __name__ == "__main__":
    main()
